import { type PageRecordConfig } from './types';

export const PAGES: PageRecordConfig[] = [
  {
    id: 'quickstart',
    name: 'Quickstart',
    filename: 'MSPY-react-01-Quickstart',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/quickstart?agent=bring-your-own',
    ideFile: 'frontend/package.json',
    startLine: 12,
    endLine: 22,
    extraTabs: [
      {
        filePath: 'frontend/src/app/quickstart/demo-chat/page.tsx',
        startLine: 28,
        endLine: 38,
      },
    ],
    demoUrl: 'http://localhost:3000/quickstart/demo-chat',
    prompt: 'Can you tell me a joke?',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'prebuilt-components',
    name: 'Prebuilt Components',
    filename: 'MSPY-react-02-PrebuiltComponents',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/prebuilt-components',
    ideFile: 'frontend/src/app/prebuilt-components/demo-chat/page.tsx',
    startLine: 58,
    endLine: 104,
    demoUrl: 'http://localhost:3000/prebuilt-components/demo-chat',
    prompt: 'What is CopilotKit?',
    prompts: ['What is CopilotKit?'],
    waitAfterPromptMs: 1500,
  },
  {
    id: 'slots',
    name: 'Custom Look and Feel - Slots',
    filename: 'MSPY-react-03-Slots',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/custom-look-and-feel/slots',
    ideFile: 'frontend/src/app/custom-look-and-feel/slots/demo-chat/page.tsx',
    startLine: 66,
    endLine: 116,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/slots/demo-chat',
    prompt: 'Hello from customized slots level 1!',
    prompts: [
      'Hello from customized slots level 1!',
      'Hello from slot level 2 props override!',
      'Hello from slot level 3 custom component!',
    ],
    waitAfterPromptMs: 1500,
  },
  {
    id: 'headless-ui',
    name: 'Custom Look and Feel - Headless UI',
    filename: 'MSPY-react-04-HeadlessUI',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/custom-look-and-feel/headless-ui',
    ideFile: 'frontend/src/app/custom-look-and-feel/headless-ui/demo-chat/page.tsx',
    startLine: 28,
    endLine: 78,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/headless-ui/demo-chat',
    prompt: 'Tell me a joke',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'programmatic-control',
    name: 'Custom Look and Feel - Programmatic Control',
    filename: 'MSPY-react-05-ProgrammaticControl',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/programmatic-control',
    ideFile: 'frontend/src/app/programmatic-control/demo-chat/page.tsx',
    startLine: 28,
    endLine: 102,
    demoUrl: 'http://localhost:3000/programmatic-control/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 1500,
  },
  {
    id: 'inspector',
    name: 'Custom Look and Feel - Inspector',
    filename: 'MSPY-react-06-Inspector',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/inspector',
    ideFile: 'frontend/src/components/providers.tsx',
    startLine: 30,
    endLine: 47,
    demoUrl: 'http://localhost:3000/inspector/demo-chat',
    prompt: 'Hello agent! Testing inspector.',
    waitAfterPromptMs: 1500,
  },
  {
    id: 'display-only',
    name: 'Generative UI - Display Only Component',
    filename: 'MSPY-react-07-DisplayOnly',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/your-components/display-only',
    ideFile: 'frontend/src/app/generative-ui/your-components/display-only/demo-chat/page.tsx',
    startLine: 27,
    endLine: 55,
    demoUrl: 'http://localhost:3000/generative-ui/your-components/display-only/demo-chat',
    prompt: 'Show the weather card for Tokyo: 77 degrees, clear',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'interactive',
    name: 'Generative UI - Interactive Component (Approval Gate)',
    filename: 'MSPY-react-08-Interactive',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/your-components/interactive',
    ideFile: 'frontend/src/app/generative-ui/your-components/interactive/demo-chat/page.tsx',
    startLine: 23,
    endLine: 64,
    demoUrl: 'http://localhost:3000/generative-ui/your-components/interactive/demo-chat',
    prompt: 'Run the command rm -rf /tmp/cache',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'tool-rendering',
    name: 'Generative UI - Tool Rendering',
    filename: 'MSPY-react-09-ToolRendering',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/tool-rendering',
    ideFile: 'frontend/src/app/generative-ui/tool-rendering/demo-chat/page.tsx',
    startLine: 23,
    endLine: 63,
    demoUrl: 'http://localhost:3000/generative-ui/tool-rendering/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 4000,
  },
  {
    id: 'state-rendering',
    name: 'Generative UI - State Rendering',
    filename: 'MSPY-react-10-StateRendering',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/state-rendering',
    ideFile: 'frontend/src/app/generative-ui/state-rendering/demo-chat/page.tsx',
    startLine: 28,
    endLine: 53,
    demoUrl: 'http://localhost:3000/generative-ui/state-rendering/demo-chat',
    prompt: 'Search for the tallest mountains, then search for the deepest oceans',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'frontend-tools',
    name: 'App Control - Frontend Tools',
    filename: 'MSPY-react-11-FrontendTools',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/frontend-tools',
    ideFile: 'frontend/src/app/frontend-tools/demo-chat/page.tsx',
    startLine: 20,
    endLine: 33,
    demoUrl: 'http://localhost:3000/frontend-tools/demo-chat',
    prompt: 'Say hello to Malaika',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'in-app-agent-read',
    name: 'Shared State - In-App Agent Read',
    filename: 'MSPY-react-12-SharedStateRead',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/shared-state/in-app-agent-read',
    ideFile: 'frontend/src/app/shared-state/in-app-agent-read/demo-chat/page.tsx',
    startLine: 20,
    endLine: 55,
    demoUrl: 'http://localhost:3000/shared-state/in-app-agent-read/demo-chat',
    prompt: 'Switch to Spanish',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'in-app-agent-write',
    name: 'Shared State - In-App Agent Write',
    filename: 'MSPY-react-13-SharedStateWrite',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/shared-state/in-app-agent-write',
    ideFile: 'frontend/src/app/shared-state/in-app-agent-write/demo-chat/page.tsx',
    startLine: 30,
    endLine: 54,
    demoUrl: 'http://localhost:3000/shared-state/in-app-agent-write/demo-chat',
    prompt: 'What language are we using now?',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'agent-app-context',
    name: 'Readables - Agent App Context',
    filename: 'MSPY-react-14-AgentAppContext',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/agent-app-context',
    ideFile: 'frontend/src/app/agent-app-context/demo-chat/page.tsx',
    startLine: 18,
    endLine: 34,
    demoUrl: 'http://localhost:3000/agent-app-context/demo-chat',
    prompt: 'Who are my colleagues?',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'auth',
    name: 'Authentication - Bearer Token',
    filename: 'MSPY-react-15-Auth',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/auth',
    ideFile: 'backend/main.py',
    startLine: 66,
    endLine: 90,
    demoUrl: 'http://localhost:3000/auth/demo-chat',
    prompt: 'Hello agent! Can you hear me?',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'copilot-runtime',
    name: 'Backend - Copilot Runtime',
    filename: 'MSPY-react-16-CopilotRuntime',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/copilot-runtime',
    ideFile: 'frontend/src/app/api/copilotkit/route.ts',
    startLine: 20,
    endLine: 43,
    demoUrl: 'http://localhost:3000/copilot-runtime/demo-chat',
    prompt: "What's the weather in Tokyo?",
    prompts: ["What's the weather in Tokyo?", 'Switch to Spanish'],
    waitAfterPromptMs: 1500,
  },
  {
    id: 'ag-ui',
    name: 'Backend - AG-UI Protocol Stream',
    filename: 'MSPY-react-17-AgUi',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/ag-ui',
    ideFile: 'frontend/src/app/ag-ui/demo-chat/page.tsx',
    startLine: 70,
    endLine: 102,
    demoUrl: 'http://localhost:3000/ag-ui/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 4000,
  },
];
