import { type PageRecordConfig } from './types';

export const PAGES: PageRecordConfig[] = [
  {
    id: 'quickstart',
    name: 'Quickstart',
    filename: '01-MSPY-react-Quickstart',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/quickstart?agent=bring-your-own',
    ideFile: 'frontend/src/app/quickstart/demo-chat/page.tsx',
    startLine: 28,
    endLine: 38,
    demoUrl: 'http://localhost:3000/quickstart/demo-chat',
    prompt: 'Can you tell me a joke?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'prebuilt-components',
    name: 'Prebuilt Components',
    filename: '02-MSPY-react-PrebuiltComponents',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/prebuilt-components',
    ideFile: 'frontend/src/app/prebuilt-components/demo-chat/page.tsx',
    startLine: 58,
    endLine: 104,
    demoUrl: 'http://localhost:3000/prebuilt-components/demo-chat',
    prompt: 'What is CopilotKit?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'slots',
    name: 'Custom Look and Feel - Slots',
    filename: '03-MSPY-react-Slots',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/custom-look-and-feel/slots',
    ideFile: 'frontend/src/app/custom-look-and-feel/slots/demo-chat/page.tsx',
    startLine: 66,
    endLine: 116,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/slots/demo-chat',
    prompt: 'Hello from customized slots!',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'headless-ui',
    name: 'Custom Look and Feel - Headless UI',
    filename: '04-MSPY-react-HeadlessUI',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/custom-look-and-feel/headless-ui',
    ideFile: 'frontend/src/app/custom-look-and-feel/headless-ui/demo-chat/page.tsx',
    startLine: 28,
    endLine: 78,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/headless-ui/demo-chat',
    prompt: 'Tell me a joke',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'programmatic-control',
    name: 'Custom Look and Feel - Programmatic Control',
    filename: '05-MSPY-react-ProgrammaticControl',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/programmatic-control',
    ideFile: 'frontend/src/app/programmatic-control/demo-chat/page.tsx',
    startLine: 28,
    endLine: 102,
    demoUrl: 'http://localhost:3000/programmatic-control/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'inspector',
    name: 'Custom Look and Feel - Inspector',
    filename: '06-MSPY-react-Inspector',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/inspector',
    ideFile: 'frontend/src/components/providers.tsx',
    startLine: 30,
    endLine: 47,
    demoUrl: 'http://localhost:3000/inspector/demo-chat',
    prompt: 'Hello agent! Testing inspector.',
    waitAfterPromptMs: 6000,
  },
  {
    id: 'display-only',
    name: 'Generative UI - Display Only Component',
    filename: '07-MSPY-react-DisplayOnly',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/your-components/display-only',
    ideFile: 'frontend/src/app/generative-ui/your-components/display-only/demo-chat/page.tsx',
    startLine: 27,
    endLine: 55,
    demoUrl: 'http://localhost:3000/generative-ui/your-components/display-only/demo-chat',
    prompt: 'Show the weather card for Tokyo: 77 degrees, clear',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'interactive',
    name: 'Generative UI - Interactive Component (Approval Gate)',
    filename: '08-MSPY-react-Interactive',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/your-components/interactive',
    ideFile: 'frontend/src/app/generative-ui/your-components/interactive/demo-chat/page.tsx',
    startLine: 23,
    endLine: 64,
    demoUrl: 'http://localhost:3000/generative-ui/your-components/interactive/demo-chat',
    prompt: 'Run the command rm -rf /tmp/cache',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'tool-rendering',
    name: 'Generative UI - Tool Rendering',
    filename: '09-MSPY-react-ToolRendering',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/tool-rendering',
    ideFile: 'frontend/src/app/generative-ui/tool-rendering/demo-chat/page.tsx',
    startLine: 23,
    endLine: 63,
    demoUrl: 'http://localhost:3000/generative-ui/tool-rendering/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'state-rendering',
    name: 'Generative UI - State Rendering',
    filename: '10-MSPY-react-StateRendering',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/state-rendering',
    ideFile: 'frontend/src/app/generative-ui/state-rendering/demo-chat/page.tsx',
    startLine: 28,
    endLine: 53,
    demoUrl: 'http://localhost:3000/generative-ui/state-rendering/demo-chat',
    prompt: 'Search for the tallest mountains, then search for the deepest oceans',
    waitAfterPromptMs: 9000,
  },
  {
    id: 'frontend-tools',
    name: 'App Control - Frontend Tools',
    filename: '11-MSPY-react-FrontendTools',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/frontend-tools',
    ideFile: 'frontend/src/app/frontend-tools/demo-chat/page.tsx',
    startLine: 20,
    endLine: 33,
    demoUrl: 'http://localhost:3000/frontend-tools/demo-chat',
    prompt: 'Say hello to Malaika',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'in-app-agent-read',
    name: 'Shared State - In-App Agent Read',
    filename: '12-MSPY-react-SharedStateRead',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/shared-state/in-app-agent-read',
    ideFile: 'frontend/src/app/shared-state/in-app-agent-read/demo-chat/page.tsx',
    startLine: 20,
    endLine: 55,
    demoUrl: 'http://localhost:3000/shared-state/in-app-agent-read/demo-chat',
    prompt: 'Switch to Spanish',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'in-app-agent-write',
    name: 'Shared State - In-App Agent Write',
    filename: '13-MSPY-react-SharedStateWrite',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/shared-state/in-app-agent-write',
    ideFile: 'frontend/src/app/shared-state/in-app-agent-write/demo-chat/page.tsx',
    startLine: 30,
    endLine: 54,
    demoUrl: 'http://localhost:3000/shared-state/in-app-agent-write/demo-chat',
    prompt: 'What language are we using now?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'agent-app-context',
    name: 'Readables - Agent App Context',
    filename: '14-MSPY-react-AgentAppContext',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/agent-app-context',
    ideFile: 'frontend/src/app/agent-app-context/demo-chat/page.tsx',
    startLine: 18,
    endLine: 34,
    demoUrl: 'http://localhost:3000/agent-app-context/demo-chat',
    prompt: 'Who are my colleagues?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'auth',
    name: 'Authentication - Bearer Token',
    filename: '15-MSPY-react-Auth',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/auth',
    ideFile: 'backend/main.py',
    startLine: 66,
    endLine: 90,
    demoUrl: 'http://localhost:3000/auth/demo-chat',
    prompt: 'Hello agent! Can you hear me?',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'copilot-runtime',
    name: 'Backend - Copilot Runtime',
    filename: '16-MSPY-react-CopilotRuntime',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/copilot-runtime',
    ideFile: 'frontend/src/app/api/copilotkit/route.ts',
    startLine: 20,
    endLine: 43,
    demoUrl: 'http://localhost:3000/copilot-runtime/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'ag-ui',
    name: 'Backend - AG-UI Protocol Stream',
    filename: '17-MSPY-react-AgUi',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/ag-ui',
    ideFile: 'frontend/src/app/ag-ui/demo-chat/page.tsx',
    startLine: 70,
    endLine: 102,
    demoUrl: 'http://localhost:3000/ag-ui/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
];
