import { type PageRecordConfig } from './types';

export const PAGES: PageRecordConfig[] = [
  {
    id: 'quickstart',
    name: 'Quickstart',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/quickstart',
    ideFile: 'frontend/src/app/quickstart/demo-chat/page.tsx',
    startLine: 28,
    endLine: 38,
    demoUrl: 'http://localhost:3000/quickstart/demo-chat',
    prompt: 'Can you tell me a joke?',
    waitAfterPromptMs: 9000,
  },
  {
    id: 'prebuilt-components',
    name: 'Prebuilt Components',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/prebuilt-components',
    ideFile: 'frontend/src/app/prebuilt-components/demo-chat/page.tsx',
    startLine: 59,
    endLine: 103,
    demoUrl: 'http://localhost:3000/prebuilt-components/demo-chat',
    prompt: 'Can you give me a brief overview of CopilotKit?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'slots',
    name: 'Custom Look and Feel - Slots',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/custom-look-and-feel/slots',
    ideFile: 'frontend/src/app/custom-look-and-feel/slots/demo-chat/page.tsx',
    startLine: 67,
    endLine: 116,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/slots/demo-chat',
    prompt: 'Hello from customized slots!',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'headless-ui',
    name: 'Custom Look and Feel - Headless UI',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/custom-look-and-feel/headless-ui',
    ideFile: 'frontend/src/app/custom-look-and-feel/headless-ui/demo-chat/page.tsx',
    startLine: 28,
    endLine: 80,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/headless-ui/demo-chat',
    prompt: 'Tell me a short joke.',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'programmatic-control',
    name: 'Programmatic Control',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/programmatic-control',
    ideFile: 'frontend/src/app/programmatic-control/demo-chat/page.tsx',
    startLine: 28,
    endLine: 100,
    demoUrl: 'http://localhost:3000/programmatic-control/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'inspector',
    name: 'Inspector',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/inspector',
    ideFile: 'frontend/src/app/inspector/demo-chat/page.tsx',
    startLine: 8,
    endLine: 30,
    demoUrl: 'http://localhost:3000/inspector/demo-chat',
    prompt: 'Hello agent! Testing inspector.',
    waitAfterPromptMs: 6000,
  },
  {
    id: 'display-only',
    name: 'Generative UI - Display Only Component',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/your-components/display-only',
    ideFile: 'frontend/src/app/generative-ui/your-components/display-only/demo-chat/page.tsx',
    startLine: 43,
    endLine: 71,
    demoUrl: 'http://localhost:3000/generative-ui/your-components/display-only/demo-chat',
    prompt: 'Show the weather card for Tokyo: 77 degrees, clear',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'interactive',
    name: 'Generative UI - Interactive Component (HITL)',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/your-components/interactive',
    ideFile: 'frontend/src/app/generative-ui/your-components/interactive/demo-chat/page.tsx',
    startLine: 23,
    endLine: 65,
    demoUrl: 'http://localhost:3000/generative-ui/your-components/interactive/demo-chat',
    prompt: 'Run the command rm -rf /tmp/cache',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'tool-rendering',
    name: 'Generative UI - Tool Rendering',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/tool-rendering',
    ideFile: 'frontend/src/app/generative-ui/tool-rendering/demo-chat/page.tsx',
    startLine: 24,
    endLine: 63,
    demoUrl: 'http://localhost:3000/generative-ui/tool-rendering/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'state-rendering',
    name: 'Generative UI - State Rendering',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/generative-ui/state-rendering',
    ideFile: 'frontend/src/app/generative-ui/state-rendering/demo-chat/page.tsx',
    startLine: 28,
    endLine: 75,
    demoUrl: 'http://localhost:3000/generative-ui/state-rendering/demo-chat',
    prompt: 'Search for the tallest mountains, then search for the deepest oceans',
    waitAfterPromptMs: 9000,
  },
  {
    id: 'frontend-tools',
    name: 'App Control - Frontend Tools',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/frontend-tools',
    ideFile: 'frontend/src/app/frontend-tools/demo-chat/page.tsx',
    startLine: 20,
    endLine: 47,
    demoUrl: 'http://localhost:3000/frontend-tools/demo-chat',
    prompt: 'Say hello to Malaika',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'in-app-agent-read',
    name: 'Shared State - Reading Agent State',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/shared-state/in-app-agent-read',
    ideFile: 'frontend/src/app/shared-state/in-app-agent-read/demo-chat/page.tsx',
    startLine: 24,
    endLine: 68,
    demoUrl: 'http://localhost:3000/shared-state/in-app-agent-read/demo-chat',
    prompt: 'Switch to Spanish',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'in-app-agent-write',
    name: 'Shared State - Writing Agent State',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/shared-state/in-app-agent-write',
    ideFile: 'frontend/src/app/shared-state/in-app-agent-write/demo-chat/page.tsx',
    startLine: 30,
    endLine: 70,
    demoUrl: 'http://localhost:3000/shared-state/in-app-agent-write/demo-chat',
    prompt: "What language are we currently speaking in?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'agent-app-context',
    name: 'App Control - Readables & Agent App Context',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/agent-app-context',
    ideFile: 'frontend/src/app/agent-app-context/demo-chat/page.tsx',
    startLine: 18,
    endLine: 62,
    demoUrl: 'http://localhost:3000/agent-app-context/demo-chat',
    prompt: 'Who are my colleagues?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'auth',
    name: 'Microsoft Agent Framework - Authentication',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/auth',
    ideFile: 'frontend/src/app/auth/demo-chat/auth-demo-chat.tsx',
    startLine: 20,
    endLine: 65,
    demoUrl: 'http://localhost:3000/auth/demo-chat',
    prompt: 'Hello, can you verify our connection?',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'copilot-runtime',
    name: 'Backend - Copilot Runtime',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/copilot-runtime',
    ideFile: 'frontend/src/app/copilot-runtime/demo-chat/page.tsx',
    startLine: 16,
    endLine: 57,
    demoUrl: 'http://localhost:3000/copilot-runtime/demo-chat',
    prompt: 'Hello my_agent! What capabilities do you have?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'ag-ui',
    name: 'Backend - AG-UI Protocol Stream',
    docUrl: 'https://docs.copilotkit.ai/ms-agent-python/ag-ui',
    ideFile: 'frontend/src/app/ag-ui/demo-chat/page.tsx',
    startLine: 70,
    endLine: 102,
    demoUrl: 'http://localhost:3000/ag-ui/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
];
