import {
  CopilotRuntime,
  CopilotKitIntelligence,
  InMemoryAgentRunner,
  createCopilotRuntimeHandler,
} from "@copilotkit/runtime/v2";
import { HttpAgent } from "@ag-ui/client";

/**
 * A dedicated runtime endpoint for the Rich Threads pages.
 *
 * While `/api/copilotkit` serves the standard agent features with in-memory
 * execution, `/api/copilotkit-threads` is configured with Enterprise Intelligence
 * to persist and manage thread histories across sessions.
 *
 * The three credentials below come from `frontend/.env.local`, copied from the
 * project `copilotkit init` scaffolded under `1cli-testing/`. Nothing here logs
 * in: `COPILOTKIT_LICENSE_TOKEN` is an EdDSA-signed JWT that
 * `@copilotkit/license-verifier` checks offline against a bundled public key.
 * `INTELLIGENCE_API_KEY` is the project key for the managed thread store, so
 * threads written here land in the same project as the CLI app.
 */

const AGENT_URL = process.env.MS_AGENT_URL ?? "http://localhost:8000";

const LICENSE_TOKEN = process.env.COPILOTKIT_LICENSE_TOKEN;

const mainAgent = () => new HttpAgent({ url: `${AGENT_URL}/` });

const runtime = new CopilotRuntime({
  // `default` is registered because `<CopilotThreadsDrawer>` and `useThreads`
  // fall back to DEFAULT_AGENT_ID ("default") when no agentId is given, and
  // threads are stored per agent id. `my_agent` mirrors the main runtime so the
  // same prompts work on both.
  agents: {
    default: mainAgent(),
    my_agent: mainAgent(),
    sample_agent: new HttpAgent({ url: `${AGENT_URL}/sample_agent` }),
    search_agent: new HttpAgent({ url: `${AGENT_URL}/search_agent` }),
  },

  // Without a license token the runtime still answers the read-only thread
  // routes off the in-memory runner's local-dev fallback (list, messages,
  // events, state). Rename/archive/delete and realtime sync return 422, and
  // `/info` omits `licenseStatus`, which leaves the prebuilt drawer locked.
  ...(LICENSE_TOKEN
    ? {
        intelligence: new CopilotKitIntelligence({
          apiKey: process.env.INTELLIGENCE_API_KEY ?? "",
          ...(process.env.INTELLIGENCE_API_URL
            ? { apiUrl: process.env.INTELLIGENCE_API_URL }
            : {}),
          ...(process.env.INTELLIGENCE_GATEWAY_WS_URL
            ? { wsUrl: process.env.INTELLIGENCE_GATEWAY_WS_URL }
            : {}),
        }),
        // Thread names are auto-generated by the LLM after the first message.
        // Spelled out rather than left to the default so the flag is visible
        // next to the docs' `generateThreadNames: false`.
        // [1] headless-threads: runtime options
        // [!code highlight]
        generateThreadNames: true,

        // Lock options from the same doc step, left at their defaults:
        // lockTtlSeconds: 20,               // max 3600
        // lockHeartbeatIntervalSeconds: 15, // max 3000
        // lockKeyPrefix: "cpk-ms-agent",    // when apps share one Redis

        // Threads are stored per user, so the runtime has to name one. The doc
        // calls a static value demo-only, and that is exactly what this is: a
        // fixed id keeps one shared list across browsers for manual QA. Send
        // `x-copilotkit-user-id` to check that two users get two separate lists.
        // [2] threads-lifecycle: scope threads to the signed-in user
        // [!code highlight]
        identifyUser: (request: Request) => {
          const id = request.headers.get("x-copilotkit-user-id") ?? "demo-user";
          return { id, name: id === "demo-user" ? "Demo User" : id };
        },
        licenseToken: LICENSE_TOKEN,
      }
    : { runner: new InMemoryAgentRunner() }),
});

const handler = createCopilotRuntimeHandler({
  runtime,
  basePath: "/api/copilotkit-threads",
});

export const GET = handler;
export const POST = handler;
export const PATCH = handler;
export const DELETE = handler;
